"""added content field to page.models.Page

Revision ID: 1249e51231af
Revises: 5a87df6dd6fe
Create Date: 2014-09-06 23:23:08.143734

"""

# revision identifiers, used by Alembic.
revision = '1249e51231af'
down_revision = '5a87df6dd6fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('content', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'content')
    ### end Alembic commands ###
