"""added date_added to page.models.Page

Revision ID: 129ca3b57215
Revises: 2b022f8c5162
Create Date: 2014-07-11 23:13:01.307656

"""

# revision identifiers, used by Alembic.
revision = '129ca3b57215'
down_revision = '2b022f8c5162'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('date_added', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'date_added')
    ### end Alembic commands ###
