"""added templates.is_base_template

Revision ID: 1972667349ee
Revises: 156eced9f514
Create Date: 2014-07-16 18:20:11.711792

"""

# revision identifiers, used by Alembic.
revision = '1972667349ee'
down_revision = '156eced9f514'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('is_base_template', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'is_base_template')
    ### end Alembic commands ###
