"""changed related_blocks pk

Revision ID: 1cce5b7b3107
Revises: 331adc4aa27f
Create Date: 2014-07-15 01:12:47.253261

"""

# revision identifiers, used by Alembic.
revision = '1cce5b7b3107'
down_revision = '331adc4aa27f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('related_blocks', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('related_blocks', 'template_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default='0')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('related_blocks', 'template_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default='0')
    op.drop_column('related_blocks', 'id')
    ### end Alembic commands ###
