"""inital schema

Revision ID: 1f69ed7e2928
Revises: None
Create Date: 2014-07-08 19:16:08.592110

"""

# revision identifiers, used by Alembic.
revision = '1f69ed7e2928'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils as sau

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('can_view', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('can_add', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('can_edit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('can_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('add_date', mysql.DATETIME(), nullable=True),
    sa.Column('_pw_hash', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], name=u'users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('templates',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('pages',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('template_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('add_to_nav', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('visible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('meta_title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('use_base_template', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['template_id'], [u'templates.id'], name=u'pages_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'pages_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('blocks',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('articles',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], [u'users.id'], name=u'articles_ibfk_1', onupdate=u'CASCADE', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('templates_blocks',
    sa.Column('template_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('block_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['block_id'], [u'blocks.id'], name=u'templates_blocks_ibfk_2'),
    sa.ForeignKeyConstraint(['template_id'], [u'templates.id'], name=u'templates_blocks_ibfk_1'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('pages_blocks',
    sa.Column('page_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('block_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['block_id'], [u'blocks.id'], name=u'pages_blocks_ibfk_2'),
    sa.ForeignKeyConstraint(['page_id'], [u'pages.id'], name=u'pages_blocks_ibfk_1'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('tags',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('types',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('html', mysql.TEXT(), nullable=True),
    sa.Column('required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('data_type', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('widgets',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_id'], [u'types.id'], name=u'widgets_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('settings',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('setting_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('default', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('value', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['setting_type_id'], [u'types.id'], name=u'settings_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('types')
    op.drop_table('blocks')
    op.drop_table('settings')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('tags')
    op.drop_table('pages_blocks')
    op.drop_table('widgets')
    op.drop_table('templates_blocks')
    op.drop_table('templates')
    op.drop_table('articles')
    op.drop_table('pages')
    from local_settings import LocalConfig
    url = LocalConfig.SQLALCHEMY_DATABASE_URI
    sau.drop_database(url)
    ### end Alembic commands ###
