"""many additions to blog.posts

Revision ID: 20d9a9ac10aa
Revises: 6e55552577c
Create Date: 2014-09-08 15:08:43.232598

"""

# revision identifiers, used by Alembic.
revision = '20d9a9ac10aa'
down_revision = '6e55552577c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.add_column(u'comments', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column(u'posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column(u'posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column(u'posts', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column(u'posts', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column(u'posts', sa.Column('excerpt_length', sa.Integer(), nullable=False))
    #op.add_column(u'posts', sa.Column('slug', sa.String(length=255), nullable=False))
    #op.create_unique_constraint(None, 'posts', ['slug','post_id'])
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('slug', 'posts',type_='unique')
    #op.drop_column(u'posts', 'slug')
    op.drop_column(u'posts', 'excerpt_length')
    op.drop_column(u'posts', 'date_modified')
    op.drop_column(u'posts', 'date_added')
    op.drop_column(u'posts', 'category_id')
    op.drop_column(u'posts', 'author_id')
    op.drop_column(u'comments', 'post_id')
    op.drop_table('posts_tags')
    ### end Alembic commands ###
