"""added AdminTab

Revision ID: 21694766dbe0
Revises: 207ca1a82b6
Create Date: 2014-08-24 22:37:05.791354

"""

# revision identifiers, used by Alembic.
revision = '21694766dbe0'
down_revision = '207ca1a82b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
