"""added page.Macro, changed page.Block

Revision ID: 26349a2988c2
Revises: 8e7a6e0be52
Create Date: 2014-07-29 17:05:38.111477

"""

# revision identifiers, used by Alembic.
revision = '26349a2988c2'
down_revision = '8e7a6e0be52'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('_args', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages_macros',
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('macro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['macro_id'], ['macros.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], )
    )
    op.add_column(u'pages', sa.Column('add_left_sidebar', sa.Boolean(), nullable=True))
    op.add_column(u'pages', sa.Column('add_right_sidebar', sa.Boolean(), nullable=True))
    op.drop_column(u'pages', 'content')
    op.drop_column(u'pages', 'add_sidebar')
    op.drop_column(u'pages', 'use_base_template')
    op.drop_column(u'templates', 'imports')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'templates', sa.Column('imports', mysql.VARCHAR(length=255), nullable=True))
    op.add_column(u'pages', sa.Column('use_base_template', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column(u'pages', sa.Column('add_sidebar', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column(u'pages', sa.Column('content', mysql.TEXT(), nullable=True))
    op.drop_column(u'pages', 'add_right_sidebar')
    op.drop_column(u'pages', 'add_left_sidebar')
    op.drop_table('pages_macros')
    op.drop_table('macros')
    ### end Alembic commands ###
