"""added field_type to types

Revision ID: 2b022f8c5162
Revises: 4b05117ecfd0
Create Date: 2014-07-11 23:09:38.320073

"""

# revision identifiers, used by Alembic.
revision = '2b022f8c5162'
down_revision = '4b05117ecfd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('types', sa.Column('field_type', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('types', 'field_type')
    ### end Alembic commands ###
