"""added admin.models.admin_panels

Revision ID: 310e1d410549
Revises: 4e0a0a40f46c
Create Date: 2014-08-16 01:05:20.780610

"""

# revision identifiers, used by Alembic.
revision = '310e1d410549'
down_revision = '4e0a0a40f46c'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_panels',
            sa.Column('id',sa.Integer,primary_key=True),
            sa.Column('name',sa.String(255),nullable=False,unique=True),
            sa.Column('content',sa.Text),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
            )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(admin_panels)
    ### end Alembic commands ###
