"""added related_blocks and associated relations and fks part 2

Revision ID: 331adc4aa27f
Revises: 343967afa2d3
Create Date: 2014-07-15 00:53:12.182643

"""

# revision identifiers, used by Alembic.
revision = '331adc4aa27f'
down_revision = '343967afa2d3'

from alembic import op
import sqlalchemy as sa
from ext import db

meta = db.metadata


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_blocks',
        sa.Column('parent_block_id',sa.Integer),
        sa.Column('child_block_id',sa.Integer),
        sa.Column('template_id',sa.Integer),
        sa.ForeignKeyConstraint(['parent_block_id'], [u'blocks.id'], name=u'blocks_ibfk_1'),
        sa.ForeignKeyConstraint(['child_block_id'], [u'blocks.id'], name=u'blocks_iafk_2'),
        sa.ForeignKeyConstraint(['template_id'], [u'templates.id'], name=u'templates_ibfk_1'),
        sa.PrimaryKeyConstraint('template_id'),
        mysql_default_charset=u'utf8',
        mysql_engine=u'InnoDB'
    )   
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_blocks')   
    ### end Alembic commands ###
