"""added related_blocks and associated relations and fks

Revision ID: 343967afa2d3
Revises: 542faa39a7c7
Create Date: 2014-07-15 00:51:27.940959

"""

# revision identifiers, used by Alembic.
revision = '343967afa2d3'
down_revision = '542faa39a7c7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    ### end Alembic commands ###
