"""added page.models.Button

Revision ID: 3635cb739a3d
Revises: 4cd505f67b57
Create Date: 2014-08-02 02:08:01.791329

"""

# revision identifiers, used by Alembic.
revision = '3635cb739a3d'
down_revision = '4cd505f67b57'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('color', sa.Enum('blue', 'yellow', 'green', 'red'), nullable=False),
    sa.Column('size', sa.Enum('XL', 'L', 'M', 'S', 'XS'), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('settings')
    op.drop_table('types')
    op.drop_table('widgets')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widgets',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_id'], [u'types.id'], name=u'widgets_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('settings',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('setting_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('default', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('value', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['setting_type_id'], [u'types.id'], name=u'settings_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('types',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('html', mysql.TEXT(), nullable=True),
    sa.Column('field_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('data_type', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('buttons')
    ### end Alembic commands ###
