"""removal of related_blocks

Revision ID: 4c0a6bfd982e
Revises: 4e084c24fd8d
Create Date: 2014-07-15 10:57:46.989306

"""

# revision identifiers, used by Alembic.
revision = '4c0a6bfd982e'
down_revision = '4e084c24fd8d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_blocks')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_blocks',
    sa.Column('parent_block_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('child_block_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('template_id', mysql.INTEGER(display_width=11), server_default='0', autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['child_block_id'], [u'blocks.id'], name=u'blocks_iafk_2'),
    sa.ForeignKeyConstraint(['parent_block_id'], [u'blocks.id'], name=u'blocks_ibfk_1'),
    sa.ForeignKeyConstraint(['template_id'], [u'templates.id'], name=u'templates_ibfk_1'),
    sa.PrimaryKeyConstraint('template_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
