"""added font_icon and font_icon_library

Revision ID: 4cb18a5ba912
Revises: 4ceba151fd52
Create Date: 2014-09-18 01:16:44.960683

"""

# revision identifiers, used by Alembic.
revision = '4cb18a5ba912'
down_revision = '4ceba151fd52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('font_icon_librarys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('call_string', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_string'),
    sa.UniqueConstraint('name')
    )
    op.create_table('font_icons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['font_icon_librarys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id','name'),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('font_icons')
    op.drop_table('font_icon_librarys')
    ### end Alembic commands ###
