"""added page.models.StaticBlock

Revision ID: 4cba90872b75
Revises: 7f4aa1e1e8
Create Date: 2014-08-02 18:02:21.191372

"""

# revision identifiers, used by Alembic.
revision = '4cba90872b75'
down_revision = '7f4aa1e1e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('block_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('static_blocks')
    ### end Alembic commands ###
