"""changed fields on pages.Template

Revision ID: 4cd505f67b57
Revises: 26349a2988c2
Create Date: 2014-07-30 17:36:18.457018

"""

# revision identifiers, used by Alembic.
revision = '4cd505f67b57'
down_revision = '26349a2988c2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('templates', 'is_base_template')
    op.drop_column('templates', 'filename')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('filename', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('templates', sa.Column('is_base_template', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('templates', 'description')
    ### end Alembic commands ###
