"""added icon_lib column to page.Button

Revision ID: 4ceba151fd52
Revises: 20d9a9ac10aa
Create Date: 2014-09-17 16:59:41.683585

"""

# revision identifiers, used by Alembic.
revision = '4ceba151fd52'
down_revision = '20d9a9ac10aa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('icon_library', sa.String(length=255), nullable=True))
    op.alter_column('posts', 'slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    #op.create_unique_constraint(None, 'posts', ['slug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique', 'posts','slug')
    op.alter_column('posts', 'slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('buttons', 'icon_library')
    ### end Alembic commands ###
