"""major changes to templates, removal of pages_blocks

Revision ID: 4e084c24fd8d
Revises: 537beb39bc22
Create Date: 2014-07-15 10:55:43.198587

"""

# revision identifiers, used by Alembic.
revision = '4e084c24fd8d'
down_revision = '537beb39bc22'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_blocks')
    op.alter_column('related_blocks', 'template_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default='0')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('blocks_ibfk_1', 'related_blocks', ['parent_block_id'], unique=False)
    op.create_index('blocks_iafk_2', 'related_blocks', ['child_block_id'], unique=False)
    op.alter_column('related_blocks', 'template_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default='0')
    op.create_table('pages_blocks',
    sa.Column('page_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('block_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['block_id'], [u'blocks.id'], name=u'pages_blocks_ibfk_2'),
    sa.ForeignKeyConstraint(['page_id'], [u'pages.id'], name=u'pages_blocks_ibfk_1'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
