"""switched fks on blog and user

Revision ID: 4e0a0a40f46c
Revises: 4cba90872b75
Create Date: 2014-08-14 02:29:57.220471

"""

# revision identifiers, used by Alembic.
revision = '4e0a0a40f46c'
down_revision = '4cba90872b75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
