"""major changes to templates, removal of templates_blocks

Revision ID: 537beb39bc22
Revises: 1cce5b7b3107
Create Date: 2014-07-15 10:50:18.018424

"""

# revision identifiers, used by Alembic.
revision = '537beb39bc22'
down_revision = '1cce5b7b3107'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils as squ
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('related_blocks', 'template_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default='0')
    op.add_column('templates', sa.Column('base_template', sa.String(length=255), nullable=True))
    op.add_column('templates', sa.Column('imports', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'imports')
    op.drop_column('templates', 'base_template')
    op.create_index('blocks_ibfk_1', 'related_blocks', ['parent_block_id'], unique=False)
    op.create_index('blocks_iafk_2', 'related_blocks', ['child_block_id'], unique=False)
    op.alter_column('related_blocks', 'template_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default='0')
    op.create_table('templates_blocks',
    sa.Column('template_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('block_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['block_id'], [u'blocks.id'], name=u'templates_blocks_ibfk_2'),
    sa.ForeignKeyConstraint(['template_id'], [u'templates.id'], name=u'templates_blocks_ibfk_1'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
