"""many changes to blog.models.Article

Revision ID: 5708b521540e
Revises: 310e1d410549
Create Date: 2014-08-18 15:52:19.310266

"""

# revision identifiers, used by Alembic.
revision = '5708b521540e'
down_revision = '310e1d410549'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_panels')
    op.add_column('articles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('tags', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('url', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('visible', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'visible')
    op.drop_column('articles', 'url')
    op.drop_column('articles', 'tags')
    op.drop_column('articles', 'meta_title')
    op.drop_column('articles', 'description')
    op.create_table('admin_panels',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
