"""added page.models.TemplateBlock, and _blocks to page.models.Template

Revision ID: 5a87df6dd6fe
Revises: 21694766dbe0
Create Date: 2014-09-05 23:58:44.977729

"""

# revision identifiers, used by Alembic.
revision = '5a87df6dd6fe'
down_revision = '21694766dbe0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id')
    )
    op.create_table('pages_template_blocks',
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('template_block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['template_block_id'], ['template_blocks.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_template_blocks')
    op.drop_table('template_blocks')
    ### end Alembic commands ###
