"""added blog.models.Post

Revision ID: 68e8945ba84
Revises: 1249e51231af
Create Date: 2014-09-07 23:32:04.110710

"""

# revision identifiers, used by Alembic.
revision = '68e8945ba84'
down_revision = '1249e51231af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    ### end Alembic commands ###
