"""added blog.models.Post relation to blog.models.Blog

Revision ID: 6e55552577c
Revises: 68e8945ba84
Create Date: 2014-09-07 23:36:56.114996

"""

# revision identifiers, used by Alembic.
revision = '6e55552577c'
down_revision = '68e8945ba84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('blog_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'blog_id')
    ### end Alembic commands ###
