"""added relationships to icon

Revision ID: 973f606b9d3
Revises: 4cb18a5ba912
Create Date: 2014-09-18 01:59:33.122141

"""

# revision identifiers, used by Alembic.
revision = '973f606b9d3'
down_revision = '4cb18a5ba912'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.add_column('buttons', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.add_column('tags', sa.Column('icon_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'icon_id')
    op.drop_column('posts', 'icon_id')
    op.drop_column('categories', 'icon_id')
    op.drop_column('buttons', 'icon_id')
    op.drop_column('blogs', 'icon_id')
    ### end Alembic commands ###
