"""added unique constraint to templates.name

Revision ID: d83f9cc0ab4
Revises: 1972667349ee
Create Date: 2014-07-19 18:44:31.087279

"""

# revision identifiers, used by Alembic.
revision = 'd83f9cc0ab4'
down_revision = '1972667349ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'templates', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates')
    ### end Alembic commands ###
