'''
    icons.py - icon library definitions
'''
#from settings import BaseConfig 

glyphicon = [
    'asterisk','plus','euro','minus','cloud',
    'envelope','pencil','glass','music','search',
    'heart','star','star-empty','user','film','th-large',
    'th','th-list','ok','remove','zoom-in','zoom-out','off',
    'signal','cog','trash','home','file','time','road',
    'download-alt','download','upload','inbox','play-circle',
    'repeat','refresh','list-alt','lock','flag','headphones',
    'volume-off','volume-down','volume-up','qrcode','barcode',
    'tag','tags','book','bookmark','print','camera','font',
    'bold','italic','text-height','text-width','align-left',
    'align-center','align-right','align-justify','list','indent-left',
    'indent-right','facetime-video','picture','map-marker','adjust',
    'tint','edit','share','check','move','step-backward','fast-backward',
    'backward','play','pause','stop','forward','fast-forward','step-forward',
    'eject','chevron-left','chevron-right','plus-sign','minus-sign','remove-sign',
    'ok-sign','question-sign','info-sign','screenshot','remove-circle','ok-circle',
    'ban-circle','arrow-left','arrow-right','arrow-up','arrow-down','share-alt',
    'resize-full','resize-small','exclamation-sign','gift','leaf','fire',
    'eye-open','eye-close','warning-sign','plane','calendar','random',
    'comment','magnet','chevron-up','chevron-down','retweet','shopping-cart',
    'folder-close','folder-open','resize-vertical','resize-horizontal','hdd',
    'bullhorn','bell','certificate','thumbs-up','thumbs-down','hand-right',
    'hand-left','hand-up','hand-down','circle-arrow-right','circle-arrow-left',
    'circle-arrow-up','circle-arrow-down','globe','wrench','tasks','filter',
    'briefcase','fullscreen','dashboard','paperclip','heart-empty','link',
    'phone','pushpin','usd','gbp','sort','sort-by-alphabet','sort-by-alphabet-alt',
    'sort-by-order','sort-by-order-alt','sort-by-attributes','sort-by-attributes-alt',
    'unchecked','expand','collapse-down','collapse-up','log-in','flash','log-out',
    'new-window','record','save','open','saved','import','export','send',
    'floppy-disk','floppy-saved','floppy-remove','floppy-save','floppy-open',
    'credit-card','transfer','cutlery','header','compressed','earphone',
    'phone-alt','tower','stats','sd-video','hd-video','subtitles','sound-stereo',
    'sound-dolby','sound-5-1','sound-6-1','sound-7-1','copyright-mark','registration-mark',
    'cloud-download','cloud-upload','tree-conifer','tree-deciduous',
    ]
        
     
# Elusive-Icons
# usage: <span class='el-icon *"></span>
elusive = [
    'zoom-out','zoom-in','youtube','wrench-alt',
    'wrench','wordpress','wheelchair','website-alt',
    'website','warning-sign','w3c','volume-up','volume-off',
    'volume-down', 'vkontakte', 'vimeo', 'view-mode', 'video-chat',
    'video-alt', 'video', 'viadeo', 'user', 'usd', 'upload',
    'unlock-alt', 'unlock', 'universal-access', 'twitter', 'tumblr',
    'trash-alt', 'trash', 'torso', 'tint', 'time-alt', 'time',
    'thumbs-up', 'thumbs-down', 'th-list', 'th-large', 'th', 'text-width',
    'text-height', 'tasks', 'tags', 'tag', 'stumbleupon', 'stop-alt',
    'stop', 'step-forward', 'step-backward', 'star-empty', 'star-alt',
    'star', 'stackoverflow', 'spotify', 'speaker', 'soundcloud', 'smiley-alt',
    'smiley', 'slideshare', 'skype', 'signal', 'shopping-cart-sign', 'shopping-cart',
    'share-alt', 'share', 'search-alt', 'search', 'screenshot', 'screen-alt',
    'screen', 'scissors', 'rss', 'road', 'reverse-alt', 'retweet', 'return-key',
    'resize-vertical', 'resize-small', 'resize-horizontal', 'resize-full', 'repeat-alt',
    'repeat', 'remove-sign', 'remove-circle', 'remove', 'refresh', 'reddit',
    'record', 'random', 'quotes-alt', 'quotes', 'question-sign', 'question',
    'qrcode', 'puzzle', 'print', 'podcast', 'plus-sign', 'plus',
    'play-circle', 'play-alt', 'play', 'plane', 'pinterest', 'picture',
    'picasa', 'photo-alt', 'photo', 'phone-alt', 'phone', 'person', 'pencil-alt',
    'pencil', 'pause-alt', 'pause', 'path', 'paper-clip-alt', 'paper-clip',
    'opensource', 'ok-sign', 'ok-circle', 'ok', 'off', 'network',
    'myspace', 'music', 'move', 'minus-sign', 'minus', 'mic-alt',
    'mic', 'map-marker-alt', 'map-marker', 'male', 'magnet', 'magic',
    'lock-alt', 'lock', 'livejournal', 'list-alt', 'list', 'linkedin',
    'link', 'lines', 'leaf', 'lastfm', 'laptop-alt', 'laptop',
    'key', 'italic', 'iphone-home', 'instagram', 'info-sign', 'indent-right',
    'indent-left', 'inbox-box', 'inbox-alt', 'inbox', 'idea-alt', 'idea',
    'hourglass', 'home-alt', 'home', 'heart-empty', 'heart-alt', 'heart',
    'hearing-impaired', 'headphones', 'hdd', 'hand-up', 'hand-right', 'hand-left',
    'hand-down', 'guidedog', 'group-alt', 'group', 'graph-alt', 'graph',
    'googleplus', 'globe-alt', 'globe', 'glasses', 'glass', 'github-text',
    'github', 'gift', 'gbp', 'fullscreen', 'friendfeed-rect', 'friendfeed',
    'foursquare', 'forward-alt', 'forward', 'fork', 'fontsize', 'font',
    'folder-sign', 'folder-open', 'folder-close', 'folder', 'flickr', 'flag-alt',
    'flag', 'fire', 'filter', 'film', 'file-new-alt', 'file-new',
    'file-edit-alt', 'file-edit', 'file-alt', 'file', 'female', 'fast-forward',
    'fast-backward', 'facetime-video', 'facebook', 'eye-open', 'eye-close',
    'exclamation-sign', 'eur', 'error-alt', 'error', 'envelope-alt', 'envelope',
    'eject', 'edit', 'dribbble', 'download-alt', 'download', 'digg',
    'deviantart', 'delicious', 'dashboard', 'css', 'credit-card', 'compass-alt',
    'compass', 'comment-alt', 'comment', 'cogs', 'cog-alt', 'cog',
    'cloud-alt', 'cloud', 'circle-arrow-up', 'circle-arrow-right', 'circle-arrow-left',
    'circle-arrow-down', 'child', 'chevron-up', 'chevron-right', 'chevron-left',
    'chevron-down', 'check-empty', 'check', 'certificate', 'cc', 'caret-up',
    'caret-right', 'caret-left', 'caret-down', 'car', 'camera', 'calendar-sign',
    'calendar', 'bullhorn', 'bulb', 'brush', 'broom', 'briefcase', 'braille',
    'bookmark-empty', 'bookmark', 'book', 'bold', 'blogger', 'blind', 'bell',
    'behance', 'barcode', 'ban-circle', 'backward', 'asl', 'arrow-up',
    'arrow-right', 'arrow-left', 'arrow-down', 'align-right', 'align-left', 'align-justify',
    'align-center', 'adult', 'adjust-alt', 'adjust', 'address-book-alt', 'address-book',
    'asterisk',
]

# octicon is optimized for 16px.
# mega-octicon is optimized for 32px but can be used larger.
# usage: <span class="octicon*"></span>
octicon = [
    "alert", "alignment-align", "alignment-aligned-to", "alignment-unalign", "arrow-down",
    "arrow-left", "arrow-right", "arrow-small-down", "arrow-small-left", "arrow-small-right",
    "arrow-small-up", "arrow-up", "beer", "book", "bookmark", "briefcase", "broadcast",
    "browser", "bug", "calendar", "check", "checklist", "chevron-down", "chevron-left",
    "chevron-right", "chevron-up", "circle-slash", "circuit-board", "clippy", "clock", "cloud-download",
    "cloud-upload", "code", "color-mode", "comment-add", "comment", "comment-discussion", "credit-card",
    "dash", "dashboard", "database", "device-camera", "device-camera-video", "device-desktop", "device-mobile",
    "diff", "diff-added", "diff-ignored", "diff-modified", "diff-removed", "diff-renamed", "ellipsis",
    "eye-unwatch", "eye-watch", "eye", "file-binary", "file-code", "file-directory", "file-media",
    "file-pdf", "file-submodule", "file-symlink-directory", "file-symlink-file", "file-text", "file-zip", "flame",
    "fold", "gear", "gift", "gist", "gist-secret", "git-branch-create", "git-branch-delete",
    "git-branch", "git-commit", "git-compare", "git-merge", "git-pull-request-abandoned", "git-pull-request", 
    "globe", "graph", "heart", "history", "home", "horizontal-rule", "hourglass", "hubot",
    "inbox", "info", "issue-closed", "issue-opened", "issue-reopened", "jersey", "jump-down",
    "jump-left", "jump-right", "jump-up", "key", "keyboard", "law", "light-bulb",
    "link", "link-external", "list-ordered", "list-unordered", "location", "gist-private", "mirror-private",
    "git-fork-private", "lock", "logo-github", "mail", "mail-read", "mail-reply", "mark-github",
    "markdown", "megaphone", "mention", "microscope", "milestone", "mirror-public", "mirror",
    "mortar-board", "move-down", "move-left", "move-right", "move-up", "mute", "no-newline",
    "octoface", "organization", "package", "paintcan", "pencil", "person-add", "person-follow",
    "person", "pin", "playback-fast-forward", "playback-pause", "playback-play", "playback-rewind", "plug",
    "repo-create", "gist-new", "file-directory-create", "file-add", "plus", "podium", "primitive-dot",
    "primitive-square", "pulse", "puzzle", "question", "quote", "radio-tower", "repo-delete",
    "repo", "repo-clone", "repo-force-push", "gist-fork", "repo-forked", "repo-pull", "repo-push",
    "rocket", "rss", "ruby", "screen-full", "screen-normal", "search-save", "search",
    "server", "settings", "log-in", "sign-in", "log-out", "sign-out", "split",
    "squirrel", "star-add", "star-delete", "star", "steps", "stop", "repo-sync",
    "sync", "tag-remove", "tag-add", "tag", "telescope", "terminal", "three-bars",
    "tools", "trashcan", "triangle-down", "triangle-left", "triangle-right", "triangle-up", "unfold",
    "unmute", "versions", "remove-close", "x", "zap", 
]


# FontAwesome
font_awesome = [
    "glass", "music", "search", "envelope-o", "heart", "star", "star-o", "user", "film", "th-large",
    "th", "th-list", "check", "remove", "close", "times", "search-plus", "search-minus", "power-off",
    "signal", "gear", "cog", "trash-o", "home", "file-o", "clock-o", "road", "download", "arrow-circle-o-down",
    "arrow-circle-o-up", "inbox", "play-circle-o", "rotate-right", "repeat", "refresh", "list-alt",
    "lock", "flag", "headphones", "volume-off", "volume-down", "volume-up", "qrcode", "barcode",
    "tag", "tags", "book", "bookmark", "print", "camera", "font", "bold", "italic", "text-height", "text-width",
    "align-left", "align-center", "align-right", "align-justify", "list", "dedent", "outdent", "indent",
    "video-camera", "photo", "image", "picture-o", "pencil", "map-marker", "adjust", "tint", "edit",
    "pencil-square-o", "share-square-o", "check-square-o", "arrows", "step-backward", "fast-backward", "backward",
    "play", "pause", "stop", "forward", "fast-forward", "step-forward", "eject", "chevron-left", "chevron-right",
    "plus-circle", "minus-circle", "times-circle", "check-circle", "question-circle", "info-circle", "crosshairs",
    "times-circle-o", "check-circle-o", "ban", "arrow-left", "arrow-right", "arrow-up", "arrow-down",
    "mail-forward", "share", "expand", "compress", "plus", "minus", "asterisk", "exclamation-circle", "gift",
    "leaf", "fire", "eye", "eye-slash", "warning", "exclamation-triangle", "plane", "calendar", "random",
    "comment", "magnet", "chevron-up", "chevron-down", "retweet", "shopping-cart", "folder", "folder-open",
    "arrows-v", "arrows-h", "bar-chart-o", "bar-chart", "twitter-square", "facebook-square", "camera-retro",
    "key", "gears", "cogs", "comments", "thumbs-o-up", "thumbs-o-down", "star-half", "heart-o", "sign-out",
    "linkedin-square", "thumb-tack", "external-link", "sign-in", "trophy", "github-square", "upload", "lemon-o",
    "phone", "square-o", "bookmark-o", "phone-square", "twitter", "facebook", "github", "unlock", "credit-card",
    "rss", "hdd-o", "bullhorn", "bell", "certificate", "hand-o-right", "hand-o-left", "hand-o-up", "hand-o-down",
    "arrow-circle-left", "arrow-circle-right", "arrow-circle-up", "arrow-circle-down", "globe", "wrench",
    "tasks", "filter", "briefcase", "arrows-alt", "group", "users", "chain", "link", "cloud", "flask", "cut",
    "scissors", "copy", "files-o", "paperclip", "save", "floppy-o", "square", "navicon", "reorder", "bars",
    "list-ul", "list-ol", "strikethrough", "underline", "table", "magic", "truck", "pinterest", 
    "pinterest-square", "google-plus-square", "google-plus", "money", "caret-down", "caret-up", "caret-left",
    "caret-right", "columns", "unsorted", "sort", "sort-down", "sort-desc", "sort-up", "sort-asc", "envelope",
    "linkedin", "rotate-left", "undo", "legal", "gavel", "dashboard", "tachometer", "comment-o", "comments-o",
    "flash", "bolt", "sitemap", "umbrella", "paste", "clipboard", "lightbulb-o", "exchange", "cloud-download",
    "cloud-upload", "user-md", "stethoscope", "suitcase", "bell-o", "coffee", "cutlery", "file-text-o",
    "building-o", "hospital-o", "ambulance", "medkit", "fighter-jet", "beer", "h-square", "plus-square",
    "angle-double-left", "angle-double-right", "angle-double-up", "angle-double-down", "angle-left",
    "angle-right", "angle-up", "angle-down", "desktop", "laptop", "tablet", "mobile-phone", "mobile", "circle-o",
    "quote-left", "quote-right", "spinner", "circle", "mail-reply", "reply", "github-alt", "folder-o",
    "folder-open-o", "smile-o", "frown-o", "meh-o", "gamepad", "keyboard-o", "flag-o", "flag-checkered",
    "terminal", "code", "mail-reply-all", "reply-all", "star-half-empty", "star-half-full", "star-half-o",
    "location-arrow", "crop", "code-fork", "unlink", "chain-broken", "question", "info",
    "exclamation", "superscript", "subscript", "eraser", "puzzle-piece", "microphone", "microphone-slash",
    "shield", "calendar-o", "fire-extinguisher", "rocket", "maxcdn", "chevron-circle-left",
    "chevron-circle-right", "chevron-circle-up", "chevron-circle-down", "html5", "css3", "anchor",
    "unlock-alt", "bullseye", "ellipsis-h", "ellipsis-v", "rss-square", "play-circle", "ticket", "minus-square",
    "minus-square-o", "level-up", "level-down", "check-square", "pencil-square", "external-link-square",
    "share-square", "compass", "toggle-down", "caret-square-o-down", "toggle-up", "caret-square-o-up",
    "toggle-right", "caret-square-o-right", "euro", "eur", "gbp", "dollar", "usd", "rupee", "inr",
    "cny", "rmb", "yen", "jpy", "ruble", "rouble", "rub", "won", "krw", "bitcoin", "btc",
    "file", "file-text", "sort-alpha-asc", "sort-alpha-desc", "sort-amount-asc", "sort-amount-desc",
    "sort-numeric-asc", "sort-numeric-desc", "thumbs-up", "thumbs-down", "youtube-square", "youtube",
    "xing", "xing-square", "youtube-play", "dropbox", "stack-overflow", "instagram", "flickr", "adn",
    "bitbucket", "bitbucket-square", "tumblr", "tumblr-square", "long-arrow-down", "long-arrow-up",
    "long-arrow-left", "long-arrow-right", "apple", "windows", "android", "linux", "dribbble", "skype",
    "foursquare", "trello", "female", "male", "gittip", "sun-o", "moon-o", "archive", "bug", "vk", "weibo",
    "renren", "pagelines", "stack-exchange", "arrow-circle-o-right", "arrow-circle-o-left", "toggle-left",
    "caret-square-o-left", "dot-circle-o", "wheelchair", "vimeo-square", "turkish-lira", "try", "plus-square-o",
    "space-shuttle", "slack", "envelope-square", "wordpress", "openid", "institution", "bank", "university",
    "mortar-board", "graduation-cap", "yahoo", "google", "reddit", "reddit-square", "stumbleupon-circle",
    "stumbleupon", "delicious", "digg", "pied-piper", "pied-piper-alt", "drupal", "joomla", "language",
    "fax", "building", "child", "paw", "spoon", "cube", "cubes", "behance", "behance-square", "steam",
    "steam-square", "recycle", "automobile", "car", "cab", "taxi", "tree", "spotify", "deviantart",
    "soundcloud", "database", "file-pdf-o", "file-word-o", "file-excel-o", "file-powerpoint-o", "file-photo-o",
    "file-picture-o", "file-image-o", "file-zip-o", "file-archive-o", "file-sound-o", "file-audio-o",
    "file-movie-o", "file-video-o", "file-code-o", "vine", "codepen", "jsfiddle", "life-bouy", "life-buoy",
    "life-saver", "support", "life-ring", "circle-o-notch", "ra", "rebel", "ge", "empire", "git-square",
    "git", "hacker-news", "tencent-weibo", "qq", "wechat", "weixin", "send", "paper-plane", "send-o",
    "paper-plane-o", "history", "circle-thin", "header", "paragraph", "sliders", "share-alt", "share-alt-square",
    "bomb", "soccer-ball-o", "futbol-o", "tty", "binoculars", "plug", "slideshare", "twitch", "yelp",
    "newspaper-o", "wifi", "calculator", "paypal", "google-wallet", "cc-visa", "cc-mastercard", "cc-discover",
    "cc-amex", "cc-paypal", "cc-stripe", "bell-slash", "bell-slash-o", "trash", "copyright", "at", "eyedropper",
    "paint-brush", "birthday-cake", "area-chart", "pie-chart", "line-chart", "lastfm", "lastfm-square",
    "toggle-off", "toggle-on", "bicycle", "bus", "ioxhost", "angellist", "cc", "shekel", "sheqel", "ils",
    "meanpath",
]




#mfg_labs = icon
# usage: <span class="icon icon-ICON"></span>

mfg_labs = [
    "cloud", "at", "plus", "minus", "arrow_up", "arrow_down", "arrow_right", "arrow_left", "chevron_down", "chevron_up", 
    "chevron_right", "chevron_left", "reorder", "list", "reorder_square", "reorder_square_line", "coverflow", "coverflow_line",
    "pause", "play", "step_forward", "step_backward", "fast_forward", "fast_backward", "cloud_upload", "cloud_download", "data_science",
    "globe", "globe_black", "math_ico", "math", "math_black", "paperplane_ico", "paperplane", "paperplane_black", "color_balance", "star", "star_half",
    "star_empty", "star_half_empty", "reload", "heart", "heart_broken", "hashtag", "reply", "retweet", "signin", "signout", "download", "upload", 
    "placepin", "display_screen","tablet", "smartphone", "connected_object", "lock", "unlock", "camera", "isight", "video_camera", "random",
    "message", "discussion", "calendar", "ringbell", "movie","mail", "pen", "settings", "measure", "vector", "vector_pen", "mute_on", "mute_off",
    "home", "sheet", "arrow_big_right", "arrow_big_left", "arrow_big_down", "arrow_big_up","dribbble_circle", "dribbble", "facebook_circle", "facebook",
    "git_circle_alt", "git_circle", "git", "octopus", "twitter_circle", "twitter", "google_plus", "linked_in_circle","linked_in", "instagram", "instagram_circle",
    "mfg_icon", "xing", "xing_circle", "mfg_icon_circle", "user", "user_male", "user_female", "users", "file_open", "file_close","file_alt", "file_close_alt",
    "attachment", "check", "cross_mark", "cancel_circle", "check_circle", "magnifying", "inbox", "clock", "stopwatch", "hourglass", "trophy",
    "unlock_alt", "lock_alt", "arrow_doubled_up", "link", "warning", "warning_alt", "magnifying_plus", "magnifying_minus", "white_question",
    "black_question", "stop","share", "eye", "trash_can", "hard_drive", "information_black", "information_white", "printer", "letter",
    "soundcloud", "soundcloud_circle", "anchor", "female_sign", "male_sign", "joystick", "high_voltage", "fire", "newspaper", "chart",
    "spread", "spinner_1", "spinner_2", "chart_alt", "label", "brush", "refresh", "node", "node_2","node_3", "link_2_nodes", "link_3_nodes", 
    "link_loop_nodes", "node_size", "node_color", "layout_directed", "layout_radial", "node_link_direction", "node_link_short_path","node_cluster", 
    "display_graph", "node_link_weight", "more_node_links", "node_shape", "node_icon", "node_text", "node_link_text", "node_link_color", "node_link_shape", "credit_card",
    "disconnect", "graph",
]

# ionicons 
# usage: <span class="ion ion-ICON"></span>
ionicon = [
    "loading-a", "alert", "alert-circled", "android-add", "android-add-contact", "android-alarm", "android-archive", "android-arrow-back", "android-arrow-down-left",
    "android-arrow-down-right", "android-arrow-forward", "android-arrow-up-left", "android-arrow-up-right", "android-battery", "android-book", "android-calendar",
    "android-call", "android-camera", "android-chat", "android-checkmark", "android-clock", "android-close", "android-contact", "android-contacts", "android-data",
    "android-developer", "android-display", "android-download", "android-drawer", "android-dropdown", "android-earth", "android-folder", "android-forums", "android-friends",
    "android-hand", "android-image", "android-inbox", "android-information", "android-keypad", "android-lightbulb", "android-locate", "android-location", "android-mail",
    "android-microphone", "android-mixer", "android-more", "android-note", "android-playstore", "android-printer", "android-promotion", "android-reminder", "android-remove",
    "android-search", "android-send", "android-settings", "android-share", "android-social", "android-social-user", "android-sort", "android-stair-drawer", "android-star",
    "android-stopwatch", "android-storage", "android-system-back", "android-system-home", "android-system-windows", "android-timer", "android-trash", "android-user-menu", "android-volume",
    "android-wifi", "aperture", "archive", "arrow-down-a", "arrow-down-b", "arrow-down-c", "arrow-expand", "arrow-graph-down-left", "arrow-graph-down-right", "arrow-graph-up-left",
    "arrow-graph-up-right", "arrow-left-a", "arrow-left-b", "arrow-left-c", "arrow-move", "arrow-resize", "arrow-return-left", "arrow-return-right", "arrow-right-a", "arrow-right-b",
    "arrow-right-c", "arrow-shrink", "arrow-swap", "arrow-up-a", "arrow-up-b", "arrow-up-c", "asterisk", "at", "bag", "battery-charging", "battery-empty", "battery-full", "battery-half",
    "battery-low", "beaker", "beer", "bluetooth", "bonfire", "bookmark", "briefcase", "bug", "calculator", "calendar", "camera", "card", "cash", "chatbox", "chatbox-working",
    "chatboxes", "chatbubble", "chatbubble-working", "chatbubbles", "checkmark", "checkmark-circled", "checkmark-round", "chevron-down", "chevron-left", "chevron-right", "chevron-up",
    "clipboard", "clock", "close", "close-circled", "close-round", "closed-captioning", "cloud", "code", "code-download", "code-working", "coffee", "compass", "compose",
    "connection-bars", "contrast", "cube", "disc", "document", "document-text", "drag", "earth", "edit", "egg", "eject", "email", "eye", "eye-disabled", "female", "filing", "film-marker",
    "fireball", "flag", "flame", "flash", "flash-off", "flask", "folder", "fork", "fork-repo", "forward", "funnel", "game-controller-a", "game-controller-b", "gear-a", "gear-b",
    "grid", "hammer", "happy", "headphone", "heart", "heart-broken", "help", "help-buoy", "help-circled", "home", "icecream", "icon-social-google-plus", "icon-social-google-plus-outline",
    "image", "images", "information", "information-circled", "ionic", "ios7-alarm", "ios7-alarm-outline", "ios7-albums", "ios7-albums-outline", "ios7-americanfootball",
    "ios7-americanfootball-outline", "ios7-analytics", "ios7-analytics-outline", "ios7-arrow-back", "ios7-arrow-down", "ios7-arrow-forward", "ios7-arrow-left", "ios7-arrow-right",
    "ios7-arrow-thin-down", "ios7-arrow-thin-left", "ios7-arrow-thin-right", "ios7-arrow-thin-up", "ios7-arrow-up", "ios7-at", "ios7-at-outline", "ios7-barcode", "ios7-barcode-outline",
    "ios7-baseball", "ios7-baseball-outline", "ios7-basketball", "ios7-basketball-outline", "ios7-bell", "ios7-bell-outline", "ios7-bolt", "ios7-bolt-outline", "ios7-bookmarks",
    "ios7-bookmarks-outline", "ios7-box", "ios7-box-outline", "ios7-briefcase", "ios7-briefcase-outline", "ios7-browsers", "ios7-browsers-outline", "ios7-calculator",
    "ios7-calculator-outline", "ios7-calendar", "ios7-calendar-outline", "ios7-camera", "ios7-camera-outline", "ios7-cart", "ios7-cart-outline", "ios7-chatboxes", "ios7-chatboxes-outline",
    "ios7-chatbubble", "ios7-chatbubble-outline", "ios7-checkmark", "ios7-checkmark-empty", "ios7-checkmark-outline", "ios7-circle-filled", "ios7-circle-outline", "ios7-clock",
    "ios7-clock-outline", "ios7-close", "ios7-close-empty", "ios7-close-outline", "ios7-cloud", "ios7-cloud-download", "ios7-cloud-download-outline", "ios7-cloud-outline",
    "ios7-cloud-upload", "ios7-cloud-upload-outline", "ios7-cloudy", "ios7-cloudy-night", "ios7-cloudy-night-outline", "ios7-cloudy-outline", "ios7-cog", "ios7-cog-outline",
    "ios7-compose", "ios7-compose-outline", "ios7-contact", "ios7-contact-outline", "ios7-copy", "ios7-copy-outline", "ios7-download", "ios7-download-outline", "ios7-drag",
    "ios7-email", "ios7-email-outline", "ios7-expand", "ios7-eye", "ios7-eye-outline", "ios7-fastforward", "ios7-fastforward-outline", "ios7-filing", "ios7-filing-outline",
    "ios7-film", "ios7-film-outline", "ios7-flag", "ios7-flag-outline", "ios7-folder", "ios7-folder-outline", "ios7-football", "ios7-football-outline", "ios7-gear",
    "ios7-gear-outline", "ios7-glasses", "ios7-glasses-outline", "ios7-heart", "ios7-heart-outline", "ios7-help", "ios7-help-empty", "ios7-help-outline", "ios7-home", "ios7-home-outline",
    "ios7-infinite", "ios7-infinite-outline", "ios7-information", "ios7-information-empty", "ios7-information-outline", "ios7-ionic-outline", "ios7-keypad", "ios7-keypad-outline",
    "ios7-lightbulb", "ios7-lightbulb-outline", "ios7-location", "ios7-location-outline", "ios7-locked", "ios7-locked-outline", "ios7-loop", "ios7-loop-strong", "ios7-medkit",
    "ios7-medkit-outline", "ios7-mic", "ios7-mic-off", "ios7-mic-outline", "ios7-minus", "ios7-minus-empty", "ios7-minus-outline", "ios7-monitor", "ios7-monitor-outline", "ios7-moon",
    "ios7-moon-outline", "ios7-more", "ios7-more-outline", "ios7-musical-note", "ios7-musical-notes", "ios7-navigate", "ios7-navigate-outline", "ios7-paper", "ios7-paper-outline",
    "ios7-paperplane", "ios7-paperplane-outline", "ios7-partlysunny", "ios7-partlysunny-outline", "ios7-pause", "ios7-pause-outline", "ios7-paw", "ios7-paw-outline", "ios7-people",
    "ios7-people-outline", "ios7-person", "ios7-person-outline", "ios7-personadd", "ios7-personadd-outline", "ios7-photos", "ios7-photos-outline", "ios7-pie", "ios7-pie-outline",
    "ios7-play", "ios7-play-outline", "ios7-plus", "ios7-plus-empty", "ios7-plus-outline", "ios7-pricetag", "ios7-pricetag-outline", "ios7-pricetags", "ios7-pricetags-outline",
    "ios7-printer", "ios7-printer-outline", "ios7-pulse", "ios7-pulse-strong", "ios7-rainy", "ios7-rainy-outline", "ios7-recording", "ios7-recording-outline", "ios7-redo",
    "ios7-redo-outline", "ios7-refresh", "ios7-refresh-empty", "ios7-refresh-outline", "ios7-reload", "ios7-reloading", "ios7-reverse-camera", "ios7-reverse-camera-outline", "ios7-rewind",
    "ios7-rewind-outline", "ios7-search", "ios7-search-strong", "ios7-settings", "ios7-settings-strong", "ios7-shrink", "ios7-skipbackward", "ios7-skipbackward-outline",
    "ios7-skipforward", "ios7-skipforward-outline", "ios7-snowy", "ios7-speedometer", "ios7-speedometer-outline", "ios7-star", "ios7-star-half", "ios7-star-outline", "ios7-stopwatch",
    "ios7-stopwatch-outline", "ios7-sunny", "ios7-sunny-outline", "ios7-telephone", "ios7-telephone-outline", "ios7-tennisball", "ios7-tennisball-outline", "ios7-thunderstorm",
    "ios7-thunderstorm-outline", "ios7-time", "ios7-time-outline", "ios7-timer", "ios7-timer-outline", "ios7-toggle", "ios7-toggle-outline", "ios7-trash", "ios7-trash-outline",
    "ios7-undo", "ios7-undo-outline", "ios7-unlocked", "ios7-unlocked-outline", "ios7-upload", "ios7-upload-outline", "ios7-videocam", "ios7-videocam-outline", "ios7-volume-high",
    "ios7-volume-low", "ios7-wineglass", "ios7-wineglass-outline", "ios7-world", "ios7-world-outline", "ipad", "iphone", "ipod", "jet", "key", "knife", "laptop", "leaf",
    "levels", "lightbulb", "link", "load-a", "loading-a", "load-b", "loading-b", "load-c", "loading-c", "load-d", "loading-d", "location", "locked", "log-in", "log-out",
    "loop", "looping", "magnet", "male", "man", "map", "medkit", "merge", "mic-a", "mic-b", "mic-c", "minus", "minus-circled", "minus-round", "model-s", "monitor",
    "more", "mouse", "music-note", "navicon", "navicon-round", "navigate", "network", "no-smoking", "nuclear", "outlet", "paper-airplane", "paperclip", "pause", "person",
    "person-add", "person-stalker", "pie-graph", "pin", "pinpoint", "pizza", "plane", "planet", "play", "playstation", "plus", "plus-circled", "plus-round",
    "podium", "pound", "power", "pricetag", "pricetags", "printer", "pull-request", "qr-scanner", "quote", "radio-waves", "record", "refresh", "refreshing", "reply", "reply-all",
    "ribbon-a", "ribbon-b", "sad", "scissors", "search", "settings", "share", "shuffle", "skip-backward", "skip-forward", "social-android", "social-android-outline", "social-apple",
    "social-apple-outline", "social-bitcoin", "social-bitcoin-outline", "social-buffer", "social-buffer-outline", "social-designernews", "social-designernews-outline", "social-dribbble",
    "social-dribbble-outline", "social-dropbox", "social-dropbox-outline", "social-facebook", "social-facebook-outline", "social-foursquare", "social-foursquare-outline",
    "social-freebsd-devil", "social-github", "social-github-outline", "social-google", "social-google-outline", "social-googleplus", "social-googleplus-outline",
    "social-hackernews", "social-hackernews-outline", "social-instagram", "social-instagram-outline", "social-linkedin", "social-linkedin-outline", "social-pinterest",
    "social-pinterest-outline", "social-reddit", "social-reddit-outline", "social-rss", "social-rss-outline", "social-skype", "social-skype-outline", "social-tumblr",
    "social-tumblr-outline", "social-tux", "social-twitter", "social-twitter-outline", "social-usd", "social-usd-outline", "social-vimeo", "social-vimeo-outline", "social-windows",
    "social-windows-outline", "social-wordpress", "social-wordpress-outline", "social-yahoo", "social-yahoo-outline", "social-youtube", "social-youtube-outline", "speakerphone",
    "speedometer", "spoon", "star", "stats-bars", "steam", "stop", "thermometer", "thumbsdown", "thumbsup", "toggle", "toggle-filled", "trash-a", "trash-b", "trophy",
    "umbrella", "university", "unlocked", "upload", "usb", "videocamera", "volume-high", "volume-low", "volume-medium", "volume-mute", "wand", "waterdrop", "wifi", "wineglass",
    "woman", "wrench", "xbox",
]

# genericons library support
# usage: <span class="genericon genericon-ICON"></span>

genericon = [
    "404", "aside", "attachment", "audio", "bold", "book", "cart", "category", "chat", "checkmark", "close", "close-alt", "cloud", "cloud-download", "cloud-upload", "code",
    "codepen", "cog", "collapse", "comment", "day", "digg", "document", "dot", "downarrow", "draggable", "dribbble", "dropbox", "dropdown", "dropdown-left", "edit", "ellipsis",
    "expand", "external", "facebook", "facebook-alt", "fastforward", "feed", "flag", "flickr", "foursquare", "fullscreen", "gallery", "github", "googleplus", "googleplus-alt", "heart",
    "help", "hide", "hierarchy", "home", "image", "info", "instagram", "italic", "key", "leftarrow", "link", "linkedin", "linkedin-alt", "location", "lock", "mail", "maximize",
    "menu", "minimize", "month", "next", "notice", "paintbrush", "path", "pause", "phone", "picture", "pinned", "pinterest", "pinterest-alt", "play", "plugin", "pocket", "polldaddy",
    "portfolio", "previous", "print", "quote", "reddit", "refresh", "reply", "reply-alt", "reply-single", "rewind", "rightarrow", "search", "send-to-phone", "send-to-tablet", "share",
    "show", "sitemap", "skip-ahead", "skip-back", "skype", "spam", "standard", "star", "status", "stop", "stumbleupon", "subscribe", "subscribed", "summary", "tablet",
    "tag", "time", "top", "trash", "tumblr", "twitter", "unapprove", "unsubscribe", "unzoom", "uparrow", "user", "video", "vimeo", "warning", "website", "week", "wordpress",
    "xpost", "youtube", "zoom",
]
